name: CI Deploy Model Predict Heart Attack

# Trigger
on:
  push:
    branches:
      - apis

  pull_request:
    branches:
      - apis

# Acciones
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repo
        uses: actions/checkout@v2

      - name: Logging in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t gab1995/deploy-proyecto-final:v1 .

      - name: Docker Push to Dockerhub
        run: docker push gab1995/deploy-proyecto-final:v1

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-heart-attack:v1
            docker stop deploy-heart-attack || true
            docker rm deploy-heart-attack || true
            docker run -d --name deploy-heart-attack -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/deploy-heart-attack:v1
